name: Build

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'main'

jobs:
  test:
    runs-on: macOS-10.15
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'
          cache: 'gradle'
      - uses: malinskiy/action-android/emulator-run-cmd@release/0.1.3
        with:
          cmd: ./gradlew integrationTest
          api: 25
